title: Mass Mesh Blog
email: contact@massmesh.org
description: >- # this means to ignore newlines until "baseurl:"
  The ISP cartel is a menace. We are here to stop them.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://massmesh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: N/A
github_username:  MassMesh

# Build settings
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
